### PR TITLE
Accounts form

### PR DESCRIPTION
**Pull request by sgassmann-skedulo**
This is a mobile extension that demonstrates how to output the related account details onto a mobile extension as a flat page. This is helpful in the use cases where there may be custom account information that resources need to view (which is currently not displayed OOTB in Skedulo Plus). 

This form currently only outputs standard account fields to ensure it's quickly deployable as a stock example. But can quickly be extended by updating the instanceFetch, ui_def and en.json files.

### CODE REVIEW

**Review by evanhollonds — CHANGES_REQUESTED** [review]
I like the idea, can we update the main readme with a description about this extension?

**Comment by sgassmann-skedulo** [comment]
Good catch @evanhollonds will update 💡

**Comment by sgassmann-skedulo** [comment]
* Updated flat page to be readonly 
* Updated readme to include AccountDetails

**Review by evanhollonds — APPROVED** [review]
Thanks!

**Pull request merged**
